sudo: required
dist: trusty

language: node_js

branches:
  only:
    - develop

node_js:
  - "4"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3" # give xvfb some time to start
  - "curl https://install.meteor.com/ | sh"
  - "npm install -g meteor-build-client"
  - "gulp update-nodes --platform linux"

script:
  - "npm run ci"

notifications:
  email:
    - mist@ethereum.org

